foldersTree = gFld("<b>strong</b>", "", "")
     insDoc(foldersTree, gLnk("Main Page", "", "main.html"))
aux1 = insFld(foldersTree, gFld("File List", "", "files.html"))
       insDoc(aux1, gLnk("prog4.cpp", "", "prog4_8cpp.html"))
       insDoc(aux1, gLnk("readgraph.cpp", "", "readgraph_8cpp.html"))
       insDoc(aux1, gLnk("readgraph.h", "", "readgraph_8h.html"))
aux1 = insFld(foldersTree, gFld("Compound List", "", "annotated.html"))
       insDoc(aux1, gLnk("ReadGraph", "", "classReadGraph.html"))
     insDoc(foldersTree, gLnk("Compound Members", "", "functions.html"))
aux1 = insFld(foldersTree, gFld("Namespace List", "", "namespaces.html"))
       insDoc(aux1, gLnk("std", "", "namespacestd.html"))
     insDoc(foldersTree, gLnk("File Members", "", "globals.html"))
