foldersTree = gFld("<b>bibtool</b>", "", "")
     insDoc(foldersTree, gLnk("Main Page", "", "main.html"))
aux1 = insFld(foldersTree, gFld("File List", "", "files.html"))
       insDoc(aux1, gLnk("bibtool.cpp", "", "bibtool_8cpp.html"))
       insDoc(aux1, gLnk("bibtool.h", "", "bibtool_8h.html"))
       insDoc(aux1, gLnk("indices.h", "", "indices_8h.html"))
       insDoc(aux1, gLnk("ndxOperations.cpp", "", "ndxOperations_8cpp.html"))
       insDoc(aux1, gLnk("prog3.cpp", "", "prog3_8cpp.html"))
aux1 = insFld(foldersTree, gFld("Compound List", "", "annotated.html"))
       insDoc(aux1, gLnk("Bibtool", "", "classBibtool.html"))
       insDoc(aux1, gLnk("bstreeBibIndex", "", "classbstreeBibIndex.html"))
       insDoc(aux1, gLnk("IndexOperations", "", "classIndexOperations.html"))
       insDoc(aux1, gLnk("rbtreeBibIndex", "", "classrbtreeBibIndex.html"))
       insDoc(aux1, gLnk("searchName", "", "structsearchName.html"))
     insDoc(foldersTree, gLnk("Compound Members", "", "functions.html"))
aux1 = insFld(foldersTree, gFld("Namespace List", "", "namespaces.html"))
       insDoc(aux1, gLnk("std", "", "namespacestd.html"))
     insDoc(foldersTree, gLnk("File Members", "", "globals.html"))
